ALTER TABLE "users" ADD CONSTRAINT "ck_users_display_name" CHECK (length(btrim(display_name)) BETWEEN 1 AND 32);
ALTER TABLE "users" ADD CONSTRAINT "ck_users_auth_version" CHECK (auth_version > 0);
ALTER TABLE "sessions" ADD CONSTRAINT "ck_sessions_token_hash" CHECK (octet_length(token_hash) = 32);
ALTER TABLE "sessions" ADD CONSTRAINT "ck_sessions_csrf" CHECK (csrf_token ~ '^[0-9a-f]{64}$');
ALTER TABLE "agents" ADD CONSTRAINT "ck_agents_name" CHECK (length(btrim(name)) BETWEEN 1 AND 50);
ALTER TABLE "agents" ADD CONSTRAINT "ck_agents_prompt" CHECK (length(btrim(system_prompt)) BETWEEN 1 AND 10000);
ALTER TABLE "agents" ADD CONSTRAINT "ck_agents_version" CHECK (config_version > 0);
ALTER TABLE "knowledge_bases" ADD CONSTRAINT "ck_knowledge_bases_name" CHECK (length(btrim(name)) BETWEEN 1 AND 50);
ALTER TABLE "conversations" ADD CONSTRAINT "ck_conversations_name" CHECK (length(btrim(name)) BETWEEN 1 AND 50);
ALTER TABLE "conversations" ADD CONSTRAINT "ck_conversations_sequence" CHECK (next_sequence_no > 0);
ALTER TABLE "messages" ADD CONSTRAINT "ck_messages_sequence" CHECK (sequence_no > 0);
ALTER TABLE "messages" ADD CONSTRAINT "ck_messages_origin" CHECK (origin IN ('user_input','answer_request','assistant'));
ALTER TABLE "messages" ADD CONSTRAINT "ck_messages_response" CHECK ((role = 'user' AND response_status IS NULL) OR (role = 'assistant' AND response_status IN ('queued','running','succeeded','failed','stopped')));
ALTER TABLE "attachments" ADD CONSTRAINT "ck_attachments_dimensions" CHECK (width > 0 AND height > 0);
ALTER TABLE "attachments" ADD CONSTRAINT "ck_attachments_expiry" CHECK ((state = 'staged' AND expires_at IS NOT NULL) OR (state = 'bound' AND expires_at IS NULL));
ALTER TABLE "files" ADD CONSTRAINT "ck_files_version" CHECK (parse_version > 0);
ALTER TABLE "document_chunks" ADD CONSTRAINT "ck_document_chunks_index" CHECK (chunk_index >= 0 AND parse_version > 0);
ALTER TABLE "document_chunks" ADD CONSTRAINT "ck_document_chunks_text" CHECK (length(btrim(content_text)) > 0);
ALTER TABLE "sources" ADD CONSTRAINT "ck_sources_title" CHECK (length(btrim(title_snapshot)) > 0);
ALTER TABLE "sources" ADD CONSTRAINT "ck_sources_url" CHECK ((kind = 'file' AND url_snapshot IS NULL) OR (kind = 'web' AND url_snapshot ~ '^https?://'));
ALTER TABLE "exercises" ADD CONSTRAINT "ck_exercises_position" CHECK (position >= 0);
ALTER TABLE "exercises" ADD CONSTRAINT "ck_exercises_question" CHECK (length(btrim(question_text)) > 0);
ALTER TABLE "exercises" ADD CONSTRAINT "ck_exercises_source_array" CHECK (jsonb_typeof(source_ids) = 'array');
ALTER TABLE "learning_plans" ADD CONSTRAINT "ck_learning_plans_name" CHECK (length(btrim(name)) BETWEEN 1 AND 50);
ALTER TABLE "learning_plans" ADD CONSTRAINT "ck_learning_plans_version" CHECK (content_version > 0);
ALTER TABLE "tasks" ADD CONSTRAINT "ck_tasks_kind" CHECK (kind IN ('chat','prompt_generate','prompt_polish','file_process','storage_cleanup'));
ALTER TABLE "tasks" ADD CONSTRAINT "ck_tasks_action" CHECK (action IS NULL OR action IN ('plan_create','plan_update','exercise','answer','tutor','feedback','clarify'));
ALTER TABLE "tasks" ADD CONSTRAINT "ck_tasks_revision" CHECK (revision > 0 AND timeout_seconds > 0);
ALTER TABLE "conversation_summaries" ADD CONSTRAINT "ck_conversation_summaries_text" CHECK (length(btrim(text)) BETWEEN 1 AND 1200);
ALTER TABLE "message_sources" ADD CONSTRAINT "ck_message_sources_position" CHECK (position >= 0);
ALTER TABLE "plan_sources" ADD CONSTRAINT "ck_plan_sources_position" CHECK (position >= 0 AND content_version > 0);
ALTER TABLE "users" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "users" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE "users" ALTER COLUMN "updated_at" SET DEFAULT now();
ALTER TABLE "users" ALTER COLUMN "theme" SET DEFAULT 'light';
ALTER TABLE "users" ALTER COLUMN "auth_version" SET DEFAULT 1;
ALTER TABLE "sessions" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "sessions" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE "sessions" ALTER COLUMN "updated_at" SET DEFAULT now();
ALTER TABLE "agents" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "agents" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE "agents" ALTER COLUMN "updated_at" SET DEFAULT now();
ALTER TABLE "agents" ALTER COLUMN "description" SET DEFAULT '';
ALTER TABLE "agents" ALTER COLUMN "config_version" SET DEFAULT 1;
ALTER TABLE "knowledge_bases" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "knowledge_bases" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE "knowledge_bases" ALTER COLUMN "updated_at" SET DEFAULT now();
ALTER TABLE "agent_knowledge_bases" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE "conversations" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "conversations" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE "conversations" ALTER COLUMN "updated_at" SET DEFAULT now();
ALTER TABLE "conversations" ALTER COLUMN "name" SET DEFAULT '新对话';
ALTER TABLE "conversations" ALTER COLUMN "next_sequence_no" SET DEFAULT 1;
ALTER TABLE "conversations" ALTER COLUMN "has_images" SET DEFAULT false;
ALTER TABLE "messages" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "messages" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE "messages" ALTER COLUMN "updated_at" SET DEFAULT now();
ALTER TABLE "messages" ALTER COLUMN "content_text" SET DEFAULT '';
ALTER TABLE "attachments" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "attachments" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE "attachments" ALTER COLUMN "updated_at" SET DEFAULT now();
ALTER TABLE "attachments" ALTER COLUMN "state" SET DEFAULT 'staged';
ALTER TABLE "message_attachments" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE "files" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "files" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE "files" ALTER COLUMN "updated_at" SET DEFAULT now();
ALTER TABLE "files" ALTER COLUMN "status" SET DEFAULT 'processing';
ALTER TABLE "files" ALTER COLUMN "parse_version" SET DEFAULT 1;
ALTER TABLE "document_chunks" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "document_chunks" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE "document_chunks" ALTER COLUMN "updated_at" SET DEFAULT now();
ALTER TABLE "sources" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "sources" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE "sources" ALTER COLUMN "updated_at" SET DEFAULT now();
ALTER TABLE "learning_plans" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "learning_plans" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE "learning_plans" ALTER COLUMN "updated_at" SET DEFAULT now();
ALTER TABLE "learning_plans" ALTER COLUMN "content_version" SET DEFAULT 1;
ALTER TABLE "message_sources" ALTER COLUMN "citation_spans" SET DEFAULT '[]'::jsonb;
ALTER TABLE "message_sources" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE "plan_sources" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE "exercises" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "exercises" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE "exercises" ALTER COLUMN "updated_at" SET DEFAULT now();
ALTER TABLE "exercises" ALTER COLUMN "source_ids" SET DEFAULT '[]'::jsonb;
ALTER TABLE "tasks" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "tasks" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE "tasks" ALTER COLUMN "updated_at" SET DEFAULT now();
ALTER TABLE "tasks" ALTER COLUMN "attempt_no" SET DEFAULT 1;
ALTER TABLE "tasks" ALTER COLUMN "status" SET DEFAULT 'queued';
ALTER TABLE "tasks" ALTER COLUMN "cancel_requested" SET DEFAULT false;
ALTER TABLE "tasks" ALTER COLUMN "revision" SET DEFAULT 1;
ALTER TABLE "tasks" ALTER COLUMN "input_snapshot" SET DEFAULT '{}'::jsonb;
ALTER TABLE "tasks" ALTER COLUMN "config_snapshot" SET DEFAULT '{}'::jsonb;
ALTER TABLE "tasks" ALTER COLUMN "result_snapshot" SET DEFAULT '{}'::jsonb;
ALTER TABLE "tasks" ALTER COLUMN "phase" SET DEFAULT 'queued';
ALTER TABLE "tasks" ALTER COLUMN "preview_text" SET DEFAULT '';
ALTER TABLE "tasks" ALTER COLUMN "timeout_seconds" SET DEFAULT 300;
ALTER TABLE "conversation_summaries" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "conversation_summaries" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE "conversation_summaries" ALTER COLUMN "updated_at" SET DEFAULT now();
ALTER TABLE "conversation_summaries" ALTER COLUMN "covered_user_message_ids" SET DEFAULT '{}'::uuid[];
ALTER TABLE "idempotency_records" ALTER COLUMN "id" SET DEFAULT gen_random_uuid();
ALTER TABLE "idempotency_records" ALTER COLUMN "created_at" SET DEFAULT now();
ALTER TABLE "idempotency_records" ALTER COLUMN "updated_at" SET DEFAULT now();
ALTER TABLE "idempotency_records" ALTER COLUMN "resource_refs" SET DEFAULT '[]'::jsonb;
